name: api_test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: API_TEST
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ./backend_api/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: ./backend_api
        run: yarn

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          character set server: "utf8"
          collation server: "utf8_general_ci"
          mysql version: "8.0"
          mysql database: "symphonia_test"
          mysql user: "dev"
          mysql password: ${{ secrets.DatabasePassword }}
      # - name: Test Api
      #   working-directory: ./backend_api
      #   run: yarn test
      #   mysql 컨테이너, 워크플로우에서 쓸 계정 정보파일이 필요 할 듯하다
