name: api_test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: API_TEST
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master

      - name: Setup MySql
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot < database/sh/init.sql

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ./backend_api/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: ./backend_api
        run: yarn
      ##!
      #! Test Api1s
      #! Done in 1.49s.
      #! Run yarn test
      #! yarn run v1.22.4
      #! $ babel-node scripts/test.js
      #! Sequelize TEST DB Initialize
      #! SequelizeConnectionError: Connection lost: The server closed the connection.
      #! ✗ TEST DB connection error. Please make sure DB is running.
      #! Done in 1.49s.
      ##!
      - name: Test Api
        working-directory: ./backend_api
        run: yarn test
